/**
 * FETCHING PRODUCTS SERVER SIDE
 */
export const FETCH_PRODUCTS_SERVER_INIT = 'CALORIES/FETCH_PRODUCTS_SERVER_INIT';
export const FETCH_PRODUCTS_SERVER_SUCCESS = 'CALORIES/FETCH_PRODUCTS_SERVER_SUCCESS';
export const FETCH_PRODUCTS_SERVER_FAILURE = 'CALORIES/FETCH_PRODUCTS_SERVER_FAILURE';
